#!/bin/sh
# build using cabal-dev

# Note: ensure cabal-dev/bin is on your PATH to ensure use of the by cabal-dev compiled wxdirect
#PATH=$HOME/Installs/wxHaskell-atze/cabal-dev/bin:$PATH
#export PATH

cd clike-lexer
cabal clean
cabal --configure --cabal-lib-version=1.16.0.3
cd ..
cd clike-ast
cabal clean
make
cd ..
cabal-dev install ./clike-lexer ./clike-ast
