#!/bin/sh

bin="../../cabal-dev/bin"
cd clike-examples/test
echo =========================== lexer: lexer ===========================
${bin}/test-lexer1 test-lexer1-1.inp
echo =========================== ast: lexer ===========================
${bin}/test-lexer1 test-ast1-1.inp
echo =========================== ast: ast ===========================
${bin}/test-ast1 test-ast1-1.inp
